#SIMPLE LINEAR REGRESSION

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
from sklearn.metrics import r2_score   #To preditct R square
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline    #industry practice, this is one after another(sequence)
from sklearn.preprocessing import StandardScaler   #Scale the input, scaling means normalizing the value
from sklearn.model_selection import train_test_split  #split the dataset

In [ ]:
data=pd.read_csv('50_Startups.csv')
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
data.isna().sum()   #null values

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [ ]:
data.dtypes

R&D Spend          float64
Administration     float64
Marketing Spend    float64
State               object
Profit             float64
dtype: object

In [ ]:
X = data[["Marketing Spend"]]
y = data["Profit"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) #random state to avoid shuffle the data points whenver calling function, ithas reproduciabilty of the object,

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(X_train.values,y_train)  #process of giving the data to the model is fit, resides with objject, fit is method to train the model, .value is optianal

LinearRegression()

In [ ]:
y_pred = lr.predict(X_test)  #to test,predict fn, fit fn to start training

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:486: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [ ]:
r2_score( y_test, y_pred)   #error is computed

-0.11205578997827947

In [ ]:
print(lr.intercept_)  #intercept_ is variable

48923.31296724075


In [ ]:
#checking the prediction   $slicing from X(complete data)
lr.predict(X[0:1])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:486: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([182462.19522503])

In [ ]:

type(lr)

sklearn.linear_model._base.LinearRegression

In [ ]:
#some bonus points.   #serialization of ML (linear regression) object
#model persistance (saving and loading trained models)
import pickle

In [ ]:
# save
with open('model.pkl','wb') as f:   #wb is write operation,f means file object
    pickle.dump(lr,f)

In [ ]:
# load
with open('model.pkl', 'rb') as f:
    clf2 = pickle.load(f)  #clf2 is model file

In [ ]:
X[0:5]   #slicing into 5 features

Marketing Spend
0        471784.10
1        443898.53
2        407934.54
3        383199.62
4        366168.42

In [ ]:
clf2.predict(X[0:5])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:486: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([182462.19522503, 174569.16142223, 164389.52411328, 157388.28441585,
       152567.58907765])

In [ ]:
# Display the first few predictions alongside the actual values
predictions = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(predictions.head())   #first row is index

       Actual      Predicted
13  134307.35  120440.331743
39   81005.76   98457.010516
30   99937.59   74718.086315
45   64926.08   49462.221939
17  125370.37  128906.206651


#MULTIPLE LINEAR REGRESSION

In [ ]:
from sklearn.model_selection import train_test_split  #no serialization is here, try it with that
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

data['State'] = label_encoder.fit_transform(data['State'])


data.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [ ]:
X = data.drop(columns=['Profit'])     #remove the particular column, that is DV, other features are taken for training
y = data['Profit']


In [ ]:
data.isna().sum()   #null values

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [ ]:
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (50, 4)
Shape of y: (50,)


In [ ]:
X = X.values
y = y.values

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print("Shape of X:", X_train.shape)
print("Shape of y:", y_train.shape)

Shape of X: (40, 4)
Shape of y: (40,)


In [ ]:
model_multiple = LinearRegression()
model_multiple.fit(X_train, y_train)

y_pred_multiple = model_multiple.predict(X_test)

mse_multiple = mean_squared_error(y_test, y_pred_multiple)
r2_multiple = r2_score(y_test, y_pred_multiple)

print("\nMultiple Linear Regression")
print(f"  Mean Squared Error: {mse_multiple:.4f}")
print(f"  R² Score: {r2_multiple:.4f}")


Multiple Linear Regression
  Mean Squared Error: 80929465.4910
  R² Score: 0.9001


In [ ]:
print(model_multiple.intercept_)


54080.71684611377


In [ ]:
#print the data type of model_multiple
type(model_multiple)

sklearn.linear_model._base.LinearRegression

In [ ]:
model_multiple.predict(X[0:5])

array([192405.36723938, 188372.32164914, 183282.8185662 , 174012.86095334,
       173529.22121764])

In [ ]:
import pandas as pd
# Display the first few predictions alongside the actual values
predictions = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred_multiple})
print(predictions.head())

      Actual      Predicted
0  134307.35  126720.661507
1   81005.76   84909.089619
2   99937.59   98890.318549
3   64926.08   46479.312402
4  125370.37  129113.183188
